### ISSUE TITLE
Simplify UI and usage

### ISSUE THREAD

**Issue by ottok** [Seravo/wp-palvelu-instance-switcher#2]
Ideally users should be able to create shadows with one click, and then switch between shadows easily, and constantly see in the taskbar clear visual feedback of what shadow they are viewing. Also the taskbar dropdown should inform the user about that SSH port this shadow has etc usability improvements.

The info shown in the taskbar should be automatic and accurate.
See https://github.com/Seravo/swd/issues/35

**Comment by anttiviljami** [comment]
another reason we need a customer API for swd

**Comment by ottok** [comment]
Roots seem to have created a similar one themselves: https://roots.io/plugins/stage-switcher/

**Comment by ottok** [comment]
Mostly done here https://github.com/Seravo/seravo-plugin/commit/95a20c776082d4fbeeaf7a82f7a8b1132e90c24c
