### ISSUE TITLE
Rewrite this plugin

### ISSUE THREAD

**Issue by anttiviljami** [Seravo/wp-palvelu-instance-switcher#4]
The entire plugin is very poor code quality, and really should be completely rewritten. 

After the rewrite, we should merge this to https://github.com/Seravo/wp-palvelu-plugin

**Comment by ottok** [comment]
Yes, in fact the feature should be implemented as a part of our must-use wp-palvelu-plugin. It was a separate plugin only due to development cycle reasons.
